# Assignment-4: Md. Rabiul Islam

In [5]:
import numpy as np

In [6]:
#Assignment Data
weight=np.array([2,4,5,3,6,5,7])
price=np.array([35,60,30,50,50,55,60])

In [7]:
weight

array([2, 4, 5, 3, 6, 5, 7])

In [8]:
price

array([35, 60, 30, 50, 50, 55, 60])

### Task 01: Manually compute the slope (M) and y-intercept (C) using Ordinary Least Squares Linear Regression

In [14]:
##Mean Calculation
mean_weight=np.mean(weight)
mean_price=np.mean(price)

In [13]:
mean_weight

4.571428571428571

In [15]:
mean_price

48.57142857142857

#Difference Calculation

In [16]:
diff_weight=weight-mean_weight
print(diff_weight)

[-2.57142857 -0.57142857  0.42857143 -1.57142857  1.42857143  0.42857143
  2.42857143]


In [17]:
diff_price=price-mean_price
print(diff_price)

[-13.57142857  11.42857143 -18.57142857   1.42857143   1.42857143
   6.42857143  11.42857143]


#Slop&Intercept_calculation

In [19]:
#slope
m = np.sum(diff_weight * diff_price) / np.sum(diff_weight**2)
print(slope_m)

2.862903225806452


In [20]:
#intercept
c = mean_price - m*mean_weight
print(c)

35.483870967741936


#Predict_price
Prediction_y = m * (input_X) + c

In [ ]:
def predict_price(weight):
    return slope_m * weight + c

In [33]:
predicted_price = predict_price(10)
print(f"vegetbale weight price: {predicted_price}")

vegetbale weight price: 64.11290322580646


### Task 02:Compute the residuals for each data point.

In [25]:
predicted_price=m*weight+c
print(predicted_price)

[41.20967742 46.93548387 49.7983871  44.07258065 52.66129032 49.7983871
 55.52419355]


In [34]:
residuals = price - predicted_price

In [27]:
residuals

array([ -6.20967742,  13.06451613, -19.7983871 ,   5.92741935,
        -2.66129032,   5.2016129 ,   4.47580645])

### Task 03: Calculate both the Mean Squared Error (MSE) and Mean Absolute Error (MAE)

In [28]:
mse = np.mean(residuals**2)
mae = np.mean(np.abs(residuals))

In [35]:
mse

98.64631336405525

In [36]:
mae

8.191244239631335

### Final Task: Generate an Excel file for the given dataset. Utilize Python for all the calculations.

In [42]:
import pandas as pd

In [43]:
#DataFrame
data = {
    'Weight': weight,
    'Actual Price': price,
    'Predicted Price': predicted_price,
    'Residual': residuals
}

df = pd.DataFrame(data)

In [41]:
pip install pandas openpyxl

Note: you may need to restart the kernel to use updated packages.


In [44]:
from openpyxl import Workbook

In [45]:
with pd.ExcelWriter('Linear_Regression_Results.xlsx', engine='openpyxl') as writer:
    df.to_excel(writer, sheet_name='Rabiul_Assignment_4', index=False)

##### Generated file in excel successfully  :  Assignmnet-4 submitted by Md. Rabiul Islam####